name: Maven Package - Multi stage docker

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jar_version: ${{ steps.version-increase.outputs.jar_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Increase Patch Version
        id: version-increase
        run: |
          POMPATH=my-app
          OLD_VERSION=$(cd $POMPATH && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          old="$OLD_VERSION"
          parts=( ${old//./ } )
          bv=$((parts[2] + 1))
          NEW_VERSION="${parts[0]}.${parts[1]}.${bv}"
          echo "pom.xml patch version at $POMPATH will be increased from $OLD_VERSION to $NEW_VERSION"
          mvn -q versions:set -DnewVersion="${NEW_VERSION}" --file $POMPATH/pom.xml
          echo ::set-output name=jar_version::${NEW_VERSION}
      - name: Docker Build
        run: |
          docker build . -t bennyroyttenberg/hw-maven-mt:${{ steps.version-increase.outputs.jar_version }} -f DockerfileMultiStage
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: |
          docker push bennyroyttenberg/hw-maven-mt:${{ steps.version-increase.outputs.jar_version }}
  
  run:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run new version Jar
        run: |
          docker run bennyroyttenberg/hw-maven:${{needs.build.outputs.jar_version}}
  
